<?php
$_['heading_title']='Перевірка перед встановленням';
$_['text_step_2']='CodeCart PRO 3.0.6.0 перевіряє сервер перед встановленням.';
$_['text_install_php']='Середовище PHP'; $_['text_install_extension']='Необхідні розширення PHP'; $_['text_install_file']='Файли конфігурації'; $_['text_install_directory']='Каталоги для запису та захищене сховище';
$_['text_setting']='Параметр'; $_['text_current']='Поточне'; $_['text_required']='Необхідне'; $_['text_extension']='Розширення'; $_['text_file']='Файл'; $_['text_directory']='Каталог'; $_['text_status']='Статус'; $_['text_on']='Увімкнено'; $_['text_off']='Вимкнено'; $_['text_missing']='Відсутнє'; $_['text_writable']='Доступний для запису'; $_['text_unwritable']='Недоступний для запису'; $_['text_version']='Версія PHP'; $_['text_file_upload']='Завантаження файлів'; $_['text_session']='Автозапуск сесії';
$_['error_missing']='Відсутній'; $_['error_unwritable']='Недоступний для запису';
$_['error_version']='Використовуйте одну підтримувану версію PHP: 8.1, 8.2, 8.3, 8.4 або 8.5.'; $_['error_file_upload']='PHP file_uploads має бути увімкнено.'; $_['error_session']='PHP session.auto_start має бути вимкнено.'; $_['error_db']='Потрібен MySQLi або PDO MySQL.'; $_['error_gd']='Потрібне розширення GD.'; $_['error_curl']='Потрібне розширення cURL.'; $_['error_openssl']='Потрібне розширення OpenSSL.'; $_['error_zlib']='Потрібне розширення ZLIB.'; $_['error_zip']='Потрібне розширення ZIP.'; $_['error_mbstring']='Потрібне розширення mbstring.'; $_['error_fileinfo']='Потрібне розширення Fileinfo.'; $_['error_iconv']='Потрібна функція iconv.'; $_['error_dom']='Потрібне розширення DOM/XML.'; $_['error_hash']='Потрібне розширення Hash.'; $_['error_xmlwriter']='Потрібне розширення XMLWriter.'; $_['error_json']='Потрібне розширення JSON.';
$_['error_catalog_writable']='Під час встановлення config.php має бути доступним для запису.'; $_['error_admin_writable']='Під час встановлення admin/config.php має бути доступним для запису.'; $_['error_image']='Каталог image має бути доступним для запису.'; $_['error_image_cache']='Каталог image/cache має бути доступним для запису.'; $_['error_image_catalog']='Каталог image/catalog має бути доступним для запису.'; $_['error_cache']='Каталог storage/cache має бути доступним для запису.'; $_['error_log']='Каталог storage/logs має бути доступним для запису.'; $_['error_download']='Каталог storage/download має бути доступним для запису.'; $_['error_upload']='Каталог storage/upload має бути доступним для запису.'; $_['error_modification']='Каталог storage/modification має бути доступним для запису.'; $_['error_session_dir']='Каталог storage/session має бути доступним для запису.'; $_['error_secure_storage_parent']='Каталог над публічним коренем сайту має бути доступним для запису, щоб створити захищене storage поза web root.';

$_['text_extension_write']='Веб-інсталятор розширень'; $_['text_extension_write_help']='Необов’язкова можливість: admin, catalog, system та image мають бути доступні PHP для запису лише якщо модулі встановлюватимуться через адмінку. Read-only код є коректним для SFTP/CI-розгортання.'; $_['text_optional']='необов’язково';

$_['error_simplexml']='Потрібне розширення SimpleXML.';
$_['error_tls12']='Потрібна підтримка TLS 1.2 або новішої версії в OpenSSL і cURL.';
